### ISSUE TITLE
Идеи по данным для базы данных

### ISSUE THREAD

**Issue by paulsoja** [OksanaZakh/ReadAloud#20]
Надо решить что мы будем хранить в базе. Для начала будут две таблички: 1 - user. В ней будут колонки id(integer), name(text), token(text), avatar_id(integer), 2 - result. Здесь будут колонки id, user.id, best_time, date. Если есть еще какие-то идеи, то пиши в комментариях.

**Comment by OksanaZakh** [comment]
В таблицу 2 можно еще добавить показатель, который будет в процентном соотношении определять на сколько правильно прочитан текст. quality_index (int).
